async function ortWasm(moduleArg={}){var moduleRtn;var e=moduleArg,aa=!!globalThis.window,g=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(l){const {createRequire:a}=await import("module");var require=a(import.meta.url)}e.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(e.va||(e.va=new Map)).set(a,b)};e.unmountExternalData=()=>{delete e.va;delete e.Da;delete e.Ca;delete e.Ea};
var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor,m="./this.program",n=(a,b)=>{throw b;},p=import.meta.url,q="",r,t;
if(l){var fs=require("fs");p.startsWith("file:")&&(q=require("path").dirname(require("url").fileURLToPath(p))+"/");t=a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a)};r=async a=>{a=u(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(m=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);n=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g){try{q=(new URL(".",p)).href}catch{}g&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);
return new Uint8Array(b.response)});r=async a=>{if(u(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ba=console.log.bind(console),v=console.error.bind(console),w,y=!1,u=a=>a.startsWith("file://"),z,A,B,C,D,E,F,G,H,I,ca=!1;function da(){var a=J.buffer;e.HEAP8=B=new Int8Array(a);D=new Int16Array(a);e.HEAPU8=C=new Uint8Array(a);new Uint16Array(a);e.HEAP32=E=new Int32Array(a);e.HEAPU32=F=new Uint32Array(a);G=new Float32Array(a);H=new Float64Array(a);I=new BigInt64Array(a);new BigUint64Array(a)}
function K(a){a="Aborted("+a+")";v(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");A?.(a);throw a;}var L;async function ea(a){if(!w)try{var b=await r(a);return new Uint8Array(b)}catch{}if(a==L&&w)a=new Uint8Array(w);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function fa(a,b){try{var c=await ea(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),K(d)}}
async function ha(a){var b=L;if(!w&&!u(b)&&!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return fa(b,a)}class ia{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}class ja{constructor(a){this.wa=a-24}}
var ka=0,la=0,ma=globalThis.TextDecoder&&new TextDecoder,na=(a,b=0,c,d)=>{b>>>=0;var f=b;c=f+c;if(d)d=c;else{for(;a[f]&&!(f>=c);)++f;d=f}if(16<d-b&&a.buffer&&ma)return ma.decode(a.subarray(b,d));for(f="";b<d;)if(c=a[b++],c&128){var h=a[b++]&63;if(192==(c&224))f+=String.fromCharCode((c&31)<<6|h);else{var k=a[b++]&63;c=224==(c&240)?(c&15)<<12|h<<6|k:(c&7)<<18|h<<12|k<<6|a[b++]&63;65536>c?f+=String.fromCharCode(c):(c-=65536,f+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else f+=String.fromCharCode(c);
return f},M=(a,b,c)=>(a>>>=0)?na(C,a,b,c):"",oa=a=>0===a%4&&(0!==a%100||0===a%400),pa=[0,31,60,91,121,152,182,213,244,274,305,335],qa=[0,31,59,90,120,151,181,212,243,273,304,334],N={},ra=a=>{if(!y)try{a()}catch(b){b instanceof ia||"unwind"==b||n(1,b)}},O=(a,b,c)=>{var d=C;b>>>=0;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var k=a.codePointAt(h);if(127>=k){if(b>=c)break;d[b++>>>0]=k}else if(2047>=k){if(b+1>=c)break;d[b++>>>0]=192|k>>6;d[b++>>>0]=128|k&63}else if(65535>=k){if(b+2>=
c)break;d[b++>>>0]=224|k>>12;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63}else{if(b+3>=c)break;d[b++>>>0]=240|k>>18;d[b++>>>0]=128|k>>12&63;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63;h++}}d[b>>>0]=0;return b-f},P=[],Q={},R=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},S=a=>{var b;return(b=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+b[1]:(b=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+b[1]:0},ta=a=>{for(var b of a)(a=
S(b))&&(Q[a]=b)};function W(a){a=Q[a>>>0];if(!a)return 0;var b;if(b=/^\s+at .*\.wasm\.(.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^\s+at (.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^(.+?)@/.exec(a))a=b[1];else return 0;ua(W.ya??0);b=R(a)+1;var c=va(b);c&&O(a,c,b);W.ya=c;return W.ya}
var X={},wa=()=>{if(!Y){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:m||"./this.program"},b;for(b in X)void 0===X[b]?delete a[b]:a[b]=X[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Y=c}return Y},Y,xa=[null,[],[]];e.wasmBinary&&(w=e.wasmBinary);e.stackSave=()=>ya();e.stackRestore=a=>za(a);e.stackAlloc=a=>Aa(a);
e.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":B[a>>>0]=b;break;case "i8":B[a>>>0]=b;break;case "i16":D[a>>>1>>>0]=b;break;case "i32":E[a>>>2>>>0]=b;break;case "i64":I[a>>>3>>>0]=BigInt(b);break;case "float":G[a>>>2>>>0]=b;break;case "double":H[a>>>3>>>0]=b;break;case "*":F[a>>>2>>>0]=b;break;default:K(`invalid type for setValue: ${c}`)}};
e.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return B[a>>>0];case "i8":return B[a>>>0];case "i16":return D[a>>>1>>>0];case "i32":return E[a>>>2>>>0];case "i64":return I[a>>>3>>>0];case "float":return G[a>>>2>>>0];case "double":return H[a>>>3>>>0];case "*":return F[a>>>2>>>0];default:K(`invalid type for getValue: ${b}`)}};e.UTF8ToString=M;e.stringToUTF8=(a,b,c)=>O(a,b,c);e.lengthBytesUTF8=R;
var Ba={1010272:(a,b,c,d,f)=>{if("undefined"==typeof e||!e.va)return 1;a=M(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=e.va.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const h=a.subarray(b,b+c);switch(f){case 0:C.set(h,d>>>0);break;case 1:e.Aa?e.Aa(d,h):e.Ba(d,h);break;default:return 4}return 0}catch{return 4}},1011096:()=>"undefined"!==typeof wasmOffsetConverter},ua,va,Ca,za,Aa,ya,J,Da={g:function(){return"undefined"!==typeof wasmOffsetConverter},
a:function(a,b,c){a>>>=0;var d=new ja(a);F[d.wa+16>>>2>>>0]=0;F[d.wa+4>>>2>>>0]=b>>>0;F[d.wa+8>>>2>>>0]=c>>>0;ka=a;la++;throw ka;},e:function(){return 0},L:function(){},w:function(){},y:function(){},M:function(){return 0},J:function(){},E:function(){},I:function(){},j:function(){},x:function(){},u:function(){},K:function(){},v:function(){},l:()=>K(""),q:()=>{},B:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);E[b>>>2>>>0]=a.getUTCSeconds();E[b+4>>>2>>>
0]=a.getUTCMinutes();E[b+8>>>2>>>0]=a.getUTCHours();E[b+12>>>2>>>0]=a.getUTCDate();E[b+16>>>2>>>0]=a.getUTCMonth();E[b+20>>>2>>>0]=a.getUTCFullYear()-1900;E[b+24>>>2>>>0]=a.getUTCDay();E[b+28>>>2>>>0]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},C:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);E[b>>>2>>>0]=a.getSeconds();E[b+4>>>2>>>0]=a.getMinutes();E[b+8>>>2>>>0]=a.getHours();E[b+12>>>2>>>0]=a.getDate();E[b+16>>>2>>>0]=a.getMonth();
E[b+20>>>2>>>0]=a.getFullYear()-1900;E[b+24>>>2>>>0]=a.getDay();E[b+28>>>2>>>0]=(oa(a.getFullYear())?pa:qa)[a.getMonth()]+a.getDate()-1|0;E[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>>2>>>0]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},D:function(a){a>>>=0;var b=new Date(E[a+20>>>2>>>0]+1900,E[a+16>>>2>>>0],E[a+12>>>2>>>0],E[a+8>>>2>>>0],E[a+4>>>2>>>0],E[a>>>2>>>0],0),c=E[a+32>>>
2>>>0],d=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(h,f);0>c?E[a+32>>>2>>>0]=Number(f!=h&&k==d):0<c!=(k==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?k:f)-d)));E[a+24>>>2>>>0]=b.getDay();E[a+28>>>2>>>0]=(oa(b.getFullYear())?pa:qa)[b.getMonth()]+b.getDate()-1|0;E[a>>>2>>>0]=b.getSeconds();E[a+4>>>2>>>0]=b.getMinutes();E[a+8>>>2>>>0]=b.getHours();E[a+12>>>2>>>0]=b.getDate();E[a+16>>>2>>>0]=b.getMonth();
E[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)},z:function(){return-52},A:function(){},r:(a,b)=>{N[a]&&(clearTimeout(N[a].id),delete N[a]);if(!b)return 0;var c=setTimeout(()=>{delete N[a];ra(()=>Ca(a,performance.now()))},b);N[a]={id:c,Fa:b};return 0},n:function(a,b,c,d){c>>>=0;d>>>=0;var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();F[a>>>0>>>2>>>0]=60*Math.max(h,f);E[b>>>0>>>2>>>0]=Number(h!=f);b=k=>{var x=Math.abs(k);
return`UTC${0<=k?"-":"+"}${String(Math.floor(x/60)).padStart(2,"0")}${String(x%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(O(a,c,17),O(b,d,17)):(O(a,d,17),O(b,c,17))},O:function(a,b,c){if(!(0<=a&&3>=a))return 28;I[c>>>0>>>3>>>0]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},k:function(a,b,c){a>>>=0;b>>>=0;c>>>=0;P.length=0;for(var d;d=C[b++>>>0];){var f=105!=d;f&=112!=d;c+=f&&c%8?4:0;P.push(112==d?F[c>>>2>>>0]:106==d?I[c>>>3>>>0]:105==d?E[c>>>2>>>0]:H[c>>>3>>>0]);c+=f?8:4}return Ba[a](...P)},
N:()=>Date.now(),c:function(a,b){return v(M(a>>>0,b>>>0))},t:function(){return 4294901760},b:()=>performance.now(),f:W,s:function(a){a>>>=0;var b=C.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-J.buffer.byteLength+65535)/65536|0;try{J.grow(d);da();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},p:function(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();
ta(a);Q.xa=S(a[3]);Q.za=a;return Q.xa},o:function(a,b,c){a>>>=0;b>>>=0;if(Q.xa==a)var d=Q.za;else d=Error().stack.toString().split("\n"),"Error"==d[0]&&d.shift(),ta(d);for(var f=3;d[f]&&S(d[f])!=a;)++f;for(a=0;a<c&&d[a+f];++a)E[b+4*a>>>2>>>0]=S(d[a+f]);return a},G:function(a,b){a>>>=0;b>>>=0;var c=0,d=0,f;for(f of wa()){var h=b+c;F[a+d>>>2>>>0]=h;c+=O(f,h,Infinity)+1;d+=4}return 0},H:function(a,b){a>>>=0;b>>>=0;var c=wa();F[a>>>2>>>0]=c.length;a=0;for(var d of c)a+=R(d)+1;F[b>>>2>>>0]=a;return 0},
d:()=>52,i:function(){return 52},F:function(){return 70},h:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;for(var f=0,h=0;h<c;h++){var k=F[b>>>2>>>0],x=F[b+4>>>2>>>0];b+=8;for(var T=0;T<x;T++){var sa=a,U=C[k+T>>>0],V=xa[sa];0===U||10===U?((1===sa?ba:v)(na(V)),V.length=0):V.push(U)}f+=x}F[d>>>2>>>0]=f;return 0},m:a=>{n(a,new ia(a))}};function Ea(){var a=Z;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.qa=b(a.qa);a.ta=b(a.ta);a.ua=(c=>()=>c()>>>0)(a.ua);return a}var Z;
Z=await (async function(){function a(c){Z=c.exports;c=Z=Ea();e._OrtInit=c.R;e._OrtGetLastError=c.S;e._OrtCreateSessionOptions=c.T;e._OrtAppendExecutionProvider=c.U;e._OrtAddFreeDimensionOverride=c.V;e._OrtAddSessionConfigEntry=c.W;e._OrtReleaseSessionOptions=c.X;e._OrtCreateSession=c.Y;e._OrtReleaseSession=c.Z;e._OrtGetInputOutputCount=c._;e._OrtGetInputOutputMetadata=c.$;e._OrtFree=c.aa;e._OrtCreateTensor=c.ba;e._OrtGetTensorData=c.ca;e._OrtReleaseTensor=c.da;e._OrtCreateRunOptions=c.ea;
e._OrtAddRunConfigEntry=c.fa;e._OrtReleaseRunOptions=c.ga;e._OrtCreateBinding=c.ha;e._OrtBindInput=c.ia;e._OrtBindOutput=c.ja;e._OrtClearBoundOutputs=c.ka;e._OrtReleaseBinding=c.la;e._OrtRunWithBinding=c.ma;e._OrtRun=c.na;e._OrtEndProfiling=c.oa;ua=e._free=c.pa;va=e._malloc=c.qa;Ca=c.ra;za=c.sa;Aa=c.ta;ya=c.ua;J=c.P;da();return Z}var b={a:Da};if(e.instantiateWasm)return new Promise(c=>{e.instantiateWasm(b,(d,f)=>{c(a(d,f))})});L??=e.locateFile?e.locateFile?e.locateFile("ort-wasm-simd.wasm",q):q+"ort-wasm-simd.wasm":
(new URL("ort-wasm-simd.wasm",import.meta.url)).href;return a((await ha(b)).instance)}());e.calledRun=!0;y||(ca=!0,Z.Q(),z?.(e));e.PTR_SIZE=4;ca?moduleRtn=e:moduleRtn=new Promise((a,b)=>{z=a;A=b});
;return moduleRtn}export default ortWasm;
